price=float(input())
discount=float(input())
vat=float(input())
base=price*(1-discount/100)
vat_amout=base*(vat/100)
total=round(base+vat_amout,2)
print(f"База после скидки: {base:.2f} ₽")
print(f"НДС:               {vat_amout:.2f} ₽")
print(f"Итого к оплате:    {total:.2f} ₽")